name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: # Specify your branches here
      - main # The 'main' branch
      - 'releases/*' # The release branches

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go environment
        uses: actions/setup-go@v3
        with:
          go-version: '1.15' # Specify your Go version
          
      - name: Run tests and generate coverage report
        run: |
          go test ./... -coverprofile=coverage.out
          mkdir -p .qodana/code-coverage
          mv coverage.out .qodana/code-coverage/
          
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.3
        with:
          args: "--baseline,qodana.sarif.json"
          pr-mode: true
          use-caches: true
          upload-result: true
          artifact-name: qodana-report
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_1640167035 }}
          QODANA_ENDPOINT: 'https://qodana.cloud'
