name: Semgrep PR Scan & HTML Report

on:
  pull_request:
    branches: [ master ]

jobs:
  semgrep-scan:
    name: semgrep-oss/scan
    runs-on: self-hosted
    
    container:
      # A Docker image with Semgrep installed. Do not change this.
      image: semgrep/semgrep
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Run Semgrep and generate JSON report
        run: semgrep scan --config auto --sarif > findings.sarif
        
      - name: Upload SARIF reports to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        if: ${{ always() }}
        with:
          sarif_file: findings.sarif
