name: SonarQube Scan

on:
  pull_request:
    branches: [ master ]


jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go environment
        uses: actions/setup-go@v3
        with:
          go-version: '1.17' # Specify your Go version
          
      - name: Install dependencies
        run: go mod download
          
      - name: Run tests and generate coverage report
        run: go test -cover -v ./... -coverprofile="coverage.out" -covermode=count -json > report.json

      - name: upload coverage file
        uses: actions/upload-artifact@v4
        with:
          name: beegoAPI-coverage
          path: coverage.out

      - name: upload report file
        uses: actions/upload-artifact@v4
        with:
          name: beegoAPI-report
          path: report.json
     
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
